### ISSUE TITLE
Figure out website/doc strategy

### ISSUE THREAD

**Issue by codymullins** [pureblazor/components#68]
Website is currently private, we also moved docs to the website for ease of use for now.

Consider-

- Moving the actual pages back to this repo as an RCL, then reference in the new project
- Open Sourcing the Website (no secrets _should_ be checked in, but we need to take an additional step to confirm or just remove history).

**Comment by tstockwell** [comment]
I am definitely going to start playing around with PB.
It would be nice at this point to have a sample app to start with.  
So, I would urge you to open the web site, or maybe produce a sample template.

As I'm writing this it occurs to me that PB probably has everything it needs to reproduce the standard Blazor template, I think I'll take a shot at that.

**Comment by codymullins** [comment]
@tstockwell we'll put it on our list to make it public this week 👍🏻 a sample with the standard Blazor template is a really good idea, too.

**Comment by codymullins** [comment]
Website has been added to the repository.
